### ISSUE TITLE
Error using system version of Elixir

### ISSUE THREAD

**Issue by gpad** [asdf-vm/asdf-elixir#39]
If I set as default Elixir version `system` like this:

```
$ cat ~/.tool-versions 
elixir system
erlang system
```

When I try to execute `mix deps.get` command I get this error

```
$ mix deps.get
Could not find Hex, which is needed to build dependency :poison
Shall I install Hex? (if running non-interactively, use: "mix local.hex --force") [Yn] Y
** (File.Error) could not make directory (with -p) "/.mix/archives/hex-0.17.1": no such file or directory
    (elixir) lib/file.ex:208: File.mkdir_p!/1
    (mix) lib/mix/tasks/archive.install.ex:91: Mix.Tasks.Archive.Install.install/3
    (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.do_install/3
    (mix) lib/mix/dep/loader.ex:143: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:302: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
```

See PR #38

**Comment by pmarreck** [comment]
I fixed this issue by adding this to my shell config dotfiles:
```
# mix config to fix an asdf issue that cropped up
export MIX_ARCHIVES="$HOME/.mix/archives"
```
Once that env var was set, the system config for asdf worked fine.
(I am hoping this now doesn't impact asdf-provided elixir versions...)

**Comment by gpad** [comment]
I created a PR #38 but I didn't receive any feedback on it ...

**Comment by Stratus3D** [comment]
Sorry for the late response here @gpad. I didn't realize I wasn't watching this repo and didn't any notifications about this. As far as the PR goes, I'm confused as to why that exec-env script is being invoked at all. I believe we have checks in asdf that skip that if we are invoking the system version. Can you retest the latest version of this plugin with the latest version of asdf and see if this is still an issue?

**Comment by gpad** [comment]
hi @Stratus3D I rebase my PR #38 with the current master and try to test it locally but I get the same error. My PR is failing on travis but I don't understand why, the error seems quite strange:

```
$ asdf plugin-test elixir https://github.com/asdf-vm/asdf-elixir.git
Cloning into '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/asdf.XXXX.wZyN5nRI'...
done.
Cloning into '/Users/travis/.asdf/plugins/elixir'...
remote: Enumerating objects: 278, done.
remote: Total 278 (delta 0), reused 0 (delta 0), pack-reused 278
Receiving objects: 100% (278/278), 33.89 KiB | 2.42 MiB/s, done.
Resolving deltas: 100% (107/107), done.
elixir/bin/list-all is using GitHub API, just be sure you provide an API Authorization token
via your travis settings. This is the current rate_limit:
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 0,
      "reset": 1539806862
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1539805779
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1539809319
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 0,
    "reset": 1539806862
  }
}
FAILED: list-all did not return any version
The command "asdf plugin-test elixir https://github.com/asdf-vm/asdf-elixir.git" exited with 1.
Done. Your build exited with 1.
```

**Comment by VirtualAirwaves** [comment]
I'm hitting this now, too! I had an saltstack file to create my environment that's worked previously and now fails:

```
        ID: mix local.hex --force
    Function: cmd.run
      Result: False
     Comment: Command "mix local.hex --force" run
     Started: 00:29:48.870971
    Duration: 2181.871 ms
     Changes:
              ----------
              pid:
                  29860
              retcode:
                  1
              stderr:
                  ** (File.Error) could not make directory (with -p) "/home/famserve/.mix/archives/hex-0.18.1": no such file or directory
                      (elixir) lib/file.ex:271: File.mkdir_p!/1
                      (mix) lib/mix/tasks/archive.install.ex:95: Mix.Tasks.Archive.Install.install/3
                      (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.local_install/3
                      (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
                      (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
              stdout:
```

**Comment by Stratus3D** [comment]
@gpad see the section of the plugin guide on rate limiting: https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md#github-api-rate-limiting You hit the GitHub API rate limit.

**Comment by Stratus3D** [comment]
Closing this issue because I believe the problem has been addressed. Let me know if this is still an issue with the latest version of asdf and asdf-elixir.
